version: "3"
services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command:
      [
        "gcloud",
        "beta",
        "emulators",
        "--verbosity=debug",
        "--user-output-enabled",
        "--log-http",
        "pubsub",
        "start",
        "--host-port=0.0.0.0:8085",
      ]
    ports:
      - "8085:8085"
